site_name: FormalMath 文档
site_url: https://example.com
repo_url: https://example.com/repo

theme:
  name: material
  language: zh

nav:
  - 首页: README.md
  - 几何学核心: docs/04-几何学/07-欧氏与非欧几何的射影视角-形式论证.md
  - 导出说明: docs/04-几何学/07-欧氏与非欧几何的射影视角-形式论证-导出说明.md
  - 风格规范: docs/STYLE.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - footnotes
  - def_list
  - attr_list 