import type { Exercise } from '../../types/exercise';

/**
 * 示例练习数据
 */
export const sampleExercises: Exercise[] = [
  {
    id: 'ex-001',
    type: 'single_choice',
    difficulty: 'beginner',
    status: 'not_started',
    title: '集合的基本概念',
    content: '设集合 $A = \\{1, 2, 3\\}$，$B = \\{2, 3, 4\\}$，则 $A \\cap B$ 等于（  ）',
    options: [
      { id: 'A', label: 'A', content: '$\\{1, 2, 3, 4\\}$' },
      { id: 'B', label: 'B', content: '$\\{2, 3\\}$' },
      { id: 'C', label: 'C', content: '$\\{1, 4\\}$' },
      { id: 'D', label: 'D', content: '$\\emptyset$' },
    ],
    correctAnswer: 'B',
    hints: [],
    maxHints: 3,
    solution: '两个集合的交集 $A \\cap B$ 是由同时属于 $A$ 和 $B$ 的所有元素组成的集合。<br><br>集合 $A = \\{1, 2, 3\\}$，集合 $B = \\{2, 3, 4\\}$。<br>共同的元素是 $2$ 和 $3$。<br>因此，$A \\cap B = \\{2, 3\\}$，答案选 B。',
    keyPoints: ['集合的交集运算', '集合的基本概念'],
    commonMistakes: ['混淆交集与并集', '遗漏共同元素'],
    subject: '基础数学',
    topic: '集合论',
    subtopic: '集合运算',
    tags: ['集合', '交集', '基础'],
    estimatedTime: 2,
    points: 5,
    prerequisites: ['集合的定义'],
    relatedConcepts: ['并集', '补集', '子集'],
  },
  {
    id: 'ex-002',
    type: 'calculation',
    difficulty: 'intermediate',
    status: 'not_started',
    title: '导数的计算',
    content: '求函数 $f(x) = x^3 - 3x^2 + 2x$ 在 $x = 1$ 处的导数值。',
    correctAnswer: '-1',
    blanks: [{ id: 'answer', position: 0, answer: '-1', tolerance: 0.01 }],
    hints: [],
    maxHints: 4,
    solution: '使用求导法则：<br><br>1. $f(x) = x^3 - 3x^2 + 2x$<br>2. $f\'(x) = 3x^2 - 6x + 2$ （幂函数求导法则）<br>3. 将 $x = 1$ 代入：<br>   $f\'(1) = 3(1)^2 - 6(1) + 2 = 3 - 6 + 2 = -1$<br><br>因此，$f\'(1) = -1$。',
    keyPoints: ['幂函数求导法则', '导数的几何意义', '代入求值'],
    commonMistakes: ['求导时指数处理错误', '符号计算错误', '忘记将x=1代入'],
    subject: '分析学',
    topic: '微积分',
    subtopic: '导数',
    tags: ['导数', '计算', '微积分'],
    estimatedTime: 5,
    points: 10,
    prerequisites: ['基本求导法则', '幂函数'],
    relatedConcepts: ['切线', '极值', '单调性'],
  },
  {
    id: 'ex-003',
    type: 'true_false',
    difficulty: 'beginner',
    status: 'not_started',
    title: '极限的性质',
    content: '若 $\\lim_{x \\to a} f(x)$ 存在且 $\\lim_{x \\to a} g(x)$ 存在，则 $\\lim_{x \\to a} [f(x) + g(x)]$ 一定存在。',
    correctAnswer: true,
    hints: [],
    maxHints: 2,
    solution: '这个命题是<b>正确</b>的。<br><br>根据极限的四则运算法则：<br>如果 $\\lim_{x \\to a} f(x) = L_1$ 且 $\\lim_{x \\to a} g(x) = L_2$ 都存在，<br>那么 $\\lim_{x \\to a} [f(x) + g(x)] = L_1 + L_2$ 也存在。<br><br>这是极限运算的基本性质。',
    keyPoints: ['极限的四则运算', '极限存在性'],
    commonMistakes: ['混淆存在性与有界性', '忽略无穷极限的特殊情况'],
    subject: '分析学',
    topic: '极限理论',
    subtopic: '极限性质',
    tags: ['极限', '性质', '判断'],
    estimatedTime: 2,
    points: 5,
    prerequisites: ['极限的定义'],
    relatedConcepts: ['连续性', '无穷小'],
  },
  {
    id: 'ex-004',
    type: 'fill_blank',
    difficulty: 'intermediate',
    status: 'not_started',
    title: '矩阵的秩',
    content: '设矩阵 $A = \\begin{pmatrix} 1 & 2 & 3 \\\\ 2 & 4 & 5 \\\\ 3 & 6 & 8 \\end{pmatrix}$，则 $\\text{rank}(A) = $ ____(1)____。',
    blanks: [
      { id: 'blank1', position: 0, answer: '2', alternatives: ['2', '二'] },
    ],
    correctAnswer: { blank1: '2' },
    hints: [],
    maxHints: 3,
    solution: '求矩阵的秩可以通过初等行变换化为行阶梯形：<br><br>$A = \\begin{pmatrix} 1 & 2 & 3 \\\\ 2 & 4 & 5 \\\\ 3 & 6 & 8 \\end{pmatrix}$<br><br>$R_2 - 2R_1 \\to R_2$:<br>$\\begin{pmatrix} 1 & 2 & 3 \\\\ 0 & 0 & -1 \\\\ 3 & 6 & 8 \\end{pmatrix}$<br><br>$R_3 - 3R_1 \\to R_3$:<br>$\\begin{pmatrix} 1 & 2 & 3 \\\\ 0 & 0 & -1 \\\\ 0 & 0 & -1 \\end{pmatrix}$<br><br>$R_3 - R_2 \\to R_3$:<br>$\\begin{pmatrix} 1 & 2 & 3 \\\\ 0 & 0 & -1 \\\\ 0 & 0 & 0 \\end{pmatrix}$<br><br>非零行数为 2，因此 $\\text{rank}(A) = 2$。',
    keyPoints: ['矩阵的秩', '初等行变换', '行阶梯形'],
    commonMistakes: ['计算错误', '忽略零行', '混淆行秩与列秩'],
    subject: '代数结构',
    topic: '线性代数',
    subtopic: '矩阵理论',
    tags: ['矩阵', '秩', '计算'],
    estimatedTime: 8,
    points: 10,
    prerequisites: ['矩阵运算', '初等变换'],
    relatedConcepts: ['行列式', '逆矩阵', '线性方程组'],
  },
  {
    id: 'ex-005',
    type: 'multiple_choice',
    difficulty: 'advanced',
    status: 'not_started',
    title: '群论基础',
    content: '下列哪些是群 $(\\mathbb{Z}, +)$ 的子群？（多选）',
    options: [
      { id: 'A', label: 'A', content: '$2\\mathbb{Z} = \\{2n : n \\in \\mathbb{Z}\\}$' },
      { id: 'B', label: 'B', content: '$\\mathbb{N}$（自然数集）' },
      { id: 'C', label: 'C', content: '$\\{0\\}$' },
      { id: 'D', label: 'D', content: '$\\{2n + 1 : n \\in \\mathbb{Z}\\}$（奇数集）' },
    ],
    correctAnswer: ['A', 'C'],
    hints: [],
    maxHints: 4,
    solution: '子群的判定条件：$H$ 是群 $G$ 的子群当且仅当：<br>1. $H$ 非空<br>2. 对任意 $a, b \\in H$，有 $ab^{-1} \\in H$<br><br>分析各选项：<br><br><b>A. $2\\mathbb{Z}$</b>：是子群。非空，且对任意 $2m, 2n \\in 2\\mathbb{Z}$，有 $2m - 2n = 2(m-n) \\in 2\\mathbb{Z}$。<br><br><b>B. $\\mathbb{N}$</b>：不是子群。不包含负数，对加法不封闭（没有逆元）。<br><br><b>C. $\\{0\\}$</b>：是子群。这是平凡子群。<br><br><b>D. 奇数集</b>：不是子群。不包含单位元 $0$，且两个奇数之和是偶数。<br><br>因此，正确答案是 A 和 C。',
    keyPoints: ['子群的定义', '子群判定定理', '群的基本性质'],
    commonMistakes: ['忽略单位元', '忘记验证逆元存在性', '混淆子群与子集'],
    subject: '代数结构',
    topic: '群论',
    subtopic: '子群理论',
    tags: ['群论', '子群', '抽象代数'],
    estimatedTime: 10,
    points: 15,
    prerequisites: ['群的定义', '群的基本性质'],
    relatedConcepts: ['正规子群', '商群', '同态'],
  },
  {
    id: 'ex-006',
    type: 'proof',
    difficulty: 'advanced',
    status: 'not_started',
    title: '证明：素数无穷多',
    content: '证明：存在无穷多个素数。',
    correctAnswer: '',
    hints: [],
    maxHints: 5,
    solution: '<b>证明（欧几里得证明法）：</b><br><br>假设素数只有有限个，记为 $p_1, p_2, \\ldots, p_n$。<br><br>构造数 $N = p_1 \\cdot p_2 \\cdot \\ldots \\cdot p_n + 1$。<br><br>考虑 $N$ 的素因子分解：<br><br>1. $N$ 必有一个素因子 $p$（因为 $N > 1$）。<br>2. $p$ 不能等于任何 $p_i$（$i = 1, 2, \\ldots, n$）。<br>   这是因为如果 $p = p_i$，则 $p$ 整除 $p_1 \\cdot p_2 \\cdot \\ldots \\cdot p_n$，<br>   但 $p$ 不整除 $1$，所以 $p$ 不整除 $N = p_1 \\cdot p_2 \\cdot \\ldots \\cdot p_n + 1$，矛盾。<br><br>因此，$p$ 是一个不在 $\\{p_1, p_2, \\ldots, p_n\\}$ 中的素数。<br><br>这与假设矛盾，故素数有无穷多个。<br><br><b>证毕。</b>',
    keyPoints: ['反证法', '素数的定义', '整除性质', '构造性证明'],
    commonMistakes: ['构造的数本身不一定是素数', '逻辑不严密', '混淆素因子与原数'],
    subject: '数论',
    topic: '素数理论',
    subtopic: '素数分布',
    tags: ['素数', '证明', '无穷', '欧几里得'],
    estimatedTime: 15,
    points: 20,
    prerequisites: ['素数的定义', '整除理论', '反证法'],
    relatedConcepts: ['算术基本定理', '素数定理', '孪生素数猜想'],
  },
];

export default sampleExercises;
