name = "FormalMathLib"
version = "0.1.0"
defaultTargets = ["FormalMathLib"]

[[lean_lib]]
name = "FormalMathLib"

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "v4.29.0"

[[lean_exe]]
name = "FormalMathLib"
root = "Main"
