name = "FormalMathLean4"
version = "0.1.0"
defaultTargets = ["FormalMathLean4"]

[[lean_lib]]
name = "FormalMathLean4"

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.19.0"


