graph TD
    %% 层次结构图 - 按学习层级组织

    limit --> continuity
    limit --> derivative
    limit --> infinite_series
    limit --> riemann_integral
    limit --> uniform_convergence
    limit --> complex_analysis
    limit --> continuous_map
    continuity --> derivative
    continuity --> riemann_integral
    continuity --> uniform_convergence
    derivative --> riemann_integral
    derivative --> differential_equations
    derivative --> complex_analysis
    derivative --> tangent_space
    derivative --> convex_function
    derivative --> finite_difference
    riemann_integral --> lebesgue_integral
    riemann_integral --> measure_theory
    riemann_integral --> differential_equations
    riemann_integral --> complex_analysis
    riemann_integral --> numerical_integration
    infinite_series --> uniform_convergence
    infinite_series --> fourier_analysis
    infinite_series --> complex_analysis
    uniform_convergence --> fourier_analysis
    uniform_convergence --> functional_analysis
    fourier_analysis --> harmonic_analysis
    fourier_analysis --> partial_differential_equations
    fourier_analysis --> spectral_method
    fourier_analysis --> fast_fourier_transform
    lebesgue_integral --> fourier_analysis
    lebesgue_integral --> lp_spaces
    lebesgue_integral --> functional_analysis
    complex_analysis --> residue_theory
    complex_analysis --> conformal_mapping
    complex_analysis --> spectral_theory
    complex_analysis --> asymptotic_analysis
    complex_analysis --> complex_geometry
    complex_analysis --> modular_form
    complex_analysis --> nyquist_criterion
    complex_analysis --> conformal_field_theory
    complex_analysis --> zeta_function
    residue_theory --> conformal_mapping
    residue_theory --> asymptotic_analysis
    harmonic_analysis --> ergodic_theory
    functional_analysis --> harmonic_analysis
    functional_analysis --> banach_space
    functional_analysis --> hilbert_space
    functional_analysis --> operator_theory
    functional_analysis --> spectral_theory
    functional_analysis --> distribution_theory
    functional_analysis --> variational_methods
    functional_analysis --> index_theorem
    measure_theory --> harmonic_analysis
    measure_theory --> lebesgue_integral
    measure_theory --> functional_analysis
    measure_theory --> probability_measure
    measure_theory --> stochastic_calculus
    measure_theory --> ergodic_theory
    set_theory --> measure_theory
    set_theory --> group
    set_theory --> group_action
    set_theory --> category_theory
    set_theory --> topological_space
    set_theory --> propositional_logic
    set_theory --> model_theory
    set_theory --> forcing
    set_theory --> large_cardinal
    set_theory --> descriptive_set_theory
    lp_spaces --> banach_space
    lp_spaces --> hilbert_space
    lp_spaces --> sobolev_spaces
    vector_space --> lp_spaces
    vector_space --> module
    vector_space --> linear_algebra
    vector_space --> matrix
    vector_space --> tensor_product
    vector_space --> group_representation
    vector_space --> lie_algebra
    vector_space --> tangent_space
    vector_space --> convex_set
    linear_algebra --> functional_analysis
    linear_algebra --> differential_equations
    linear_algebra --> group_representation
    linear_algebra --> regression_analysis
    linear_algebra --> optimization_problem
    linear_algebra --> conjugate_gradient
    linear_algebra --> linear_programming
    linear_algebra --> control_system
    linear_algebra --> iterative_method
    linear_algebra --> numerical_linear_algebra
    linear_algebra --> pca
    linear_algebra --> neural_network
    banach_space --> operator_theory
    hilbert_space --> spectral_theory
    hilbert_space --> quantum_mechanics
    hilbert_space --> operator_theory
    operator_theory --> spectral_theory
    operator_theory --> quantum_mechanics
    spectral_theory --> integrable_system
    distribution_theory --> sobolev_spaces
    distribution_theory --> partial_differential_equations
    sobolev_spaces --> partial_differential_equations
    sobolev_spaces --> variational_methods
    sobolev_spaces --> finite_element
    variational_methods --> optimal_control
    variational_methods --> finite_element
    variational_methods --> classical_mechanics
    differential_equations --> partial_differential_equations
    differential_equations --> optimal_control
    differential_equations --> control_system
    differential_equations --> sde
    differential_equations --> population_dynamics
    differential_equations --> neural_dynamics
    differential_equations --> numerical_ode
    differential_equations --> classical_mechanics
    differential_equations --> hamiltonian_system
    differential_equations --> nonlinear_dynamics
    partial_differential_equations --> fluid_dynamics
    partial_differential_equations --> reaction_diffusion
    partial_differential_equations --> numerical_pde
    partial_differential_equations --> schrodinger_equation
    group --> ring
    group --> group_representation
    group --> group_action
    group --> lie_group
    group --> vector_space
    group --> character_theory
    group --> sylow_theory
    group --> category_theory
    group --> fundamental_group
    group --> primitive_root
    group --> elliptic_curve
    group --> symmetric_encryption
    group --> groupoid
    group --> group_cohomology
    group --> induced_representation
    ring --> field
    ring --> module
    ring --> commutative_algebra
    ring --> algebraic_geometry
    ring --> algebraic_integer
    ring --> ideal
    ring --> homomorphic_encryption
    ring --> valuation
    field --> vector_space
    field --> valuation
    module --> homological_algebra
    module --> commutative_algebra
    module --> tensor_product
    module --> cohomology
    module --> ext_functor
    module --> tilting_theory
    matrix --> linear_algebra
    matrix --> eigenvalue
    matrix --> jordan_normal_form
    matrix --> numerical_linear_algebra
    matrix --> hessian_matrix
    matrix --> state_space
    matrix --> sparse_matrix
    eigenvalue --> jordan_normal_form
    eigenvalue --> spectral_theory
    eigenvalue --> stability_analysis
    eigenvalue --> root_locus
    eigenvalue --> pca
    tensor_product --> tensor_field
    tensor_product --> monoidal_category
    tensor_product --> tor_functor
    homological_algebra --> derived_category
    homological_algebra --> group_cohomology
    homological_algebra --> sheaf_cohomology
    homological_algebra --> cohomology_sheaf
    homological_algebra --> homotopy_algebra
    homological_algebra --> abelian_category
    homological_algebra --> triangulated_category
    homological_algebra --> derived_functor_cat
    homological_algebra --> tor_functor
    homological_algebra --> ext_functor
    category_theory --> homological_algebra
    category_theory --> sheaf
    category_theory --> homotopy_algebra
    category_theory --> higher_category
    category_theory --> model_category
    category_theory --> simplicial_set
    category_theory --> monoidal_category
    category_theory --> abelian_category
    category_theory --> topos
    category_theory --> enriched_category
    category_theory --> 2_category
    category_theory --> fibered_category
    category_theory --> limits_colimits
    category_theory --> yoneda_lemma
    category_theory --> groupoid
    category_theory --> motive
    category_theory --> moduli_space
    category_theory --> categorical_logic
    group_representation --> character_theory
    group_representation --> lie_group
    group_representation --> galois_representation
    group_action --> sylow_theory
    group_action --> group_cohomology
    group_action --> modular_form
    sylow_theory --> solvable_group
    lie_group --> lie_algebra
    lie_group --> fiber_bundle
    lie_group --> characteristic_class
    lie_group --> automorphic_form
    lie_group --> gauge_theory
    lie_algebra --> quantum_field_theory
    lie_algebra --> representation_lie_algebra
    lie_algebra --> category_O
    commutative_algebra --> algebraic_geometry
    commutative_algebra --> scheme
    ideal --> commutative_algebra
    ideal --> class_number
    algebraic_geometry --> scheme
    algebraic_geometry --> sheaf
    algebraic_geometry --> cohomology_sheaf
    algebraic_geometry --> arithmetic_geometry
    algebraic_geometry --> motive
    algebraic_geometry --> intersection_theory
    algebraic_geometry --> chow_ring
    algebraic_geometry --> biration_geometry
    algebraic_geometry --> derived_algebraic_geometry
    algebraic_geometry --> elliptic_curve
    algebraic_geometry --> abelian_variety
    algebraic_geometry --> diophantine_geometry
    scheme --> cohomology_sheaf
    scheme --> moduli_space
    scheme --> algebraic_stack
    scheme --> etale_cohomology
    scheme --> crystalline_cohomology
    scheme --> biration_geometry
    scheme --> arithmetic_geometry
    sheaf --> scheme
    sheaf --> cohomology_sheaf
    cohomology_sheaf --> hodge_theory
    homotopy_algebra --> infinity_category
    topological_space --> continuous_map
    topological_space --> compactness
    topological_space --> connectedness
    topological_space --> homotopy
    topological_space --> manifold
    continuous_map --> homotopy
    continuous_map --> covering_space
    continuous_map --> compactness
    continuous_map --> connectedness
    connectedness --> fundamental_group
    homotopy --> fundamental_group
    homotopy --> homology_group
    homotopy --> covering_space
    fundamental_group --> covering_space
    fundamental_group --> algebraic_topology
    homology_group --> cohomology
    homology_group --> algebraic_topology
    homology_group --> morse_theory
    cohomology --> de_rham_cohomology
    cohomology --> characteristic_class
    cohomology --> cohomology_sheaf
    cohomology --> index_theorem
    cohomology --> algebraic_topology
    cohomology --> spectral_sequence
    cohomology --> group_cohomology
    cohomology --> sheaf_cohomology
    cohomology --> motive
    cohomology --> chow_ring
    manifold --> tangent_space
    manifold --> differential_form
    manifold --> riemannian_metric
    manifold --> tensor_field
    manifold --> fiber_bundle
    manifold --> morse_theory
    manifold --> symplectic_geometry
    manifold --> complex_geometry
    tangent_space --> tensor_field
    tangent_space --> lie_group
    tangent_space --> differential_form
    tensor_field --> riemannian_metric
    tensor_field --> curvature
    differential_form --> stokes_theorem
    differential_form --> de_rham_cohomology
    differential_form --> symplectic_geometry
    stokes_theorem --> de_rham_cohomology
    stokes_theorem --> index_theorem
    riemannian_metric --> curvature
    riemannian_metric --> geodesic
    riemannian_metric --> connection
    connection --> curvature
    connection --> geodesic
    fiber_bundle --> characteristic_class
    fiber_bundle --> gauge_theory
    fiber_bundle --> fibered_category
    characteristic_class --> index_theorem
    symplectic_geometry --> hamiltonian
    symplectic_geometry --> hamiltonian_system
    complex_geometry --> hodge_theory
    algebraic_topology --> spectral_sequence
    algebraic_topology --> simplicial_set
    algebraic_topology --> conley_index
    divisibility --> congruence
    congruence --> primitive_root
    congruence --> quadratic_residue
    quadratic_residue --> class_field_theory
    algebraic_integer --> ideal
    elliptic_curve --> modular_form
    elliptic_curve --> arithmetic_geometry
    elliptic_curve --> elliptic_curve_crypto
    modular_form --> l_function
    modular_form --> automorphic_form
    arithmetic_geometry --> diophantine_geometry
    p_adic_numbers --> galois_representation
    valuation --> p_adic_numbers
    valuation --> p_adic_number
    galois_representation --> langlands_program
    automorphic_form --> langlands_program
    propositional_logic --> predicate_logic
    propositional_logic --> proof_theory
    propositional_logic --> intuitionistic_logic
    propositional_logic --> modal_logic
    predicate_logic --> model_theory
    predicate_logic --> proof_theory
    predicate_logic --> recursion_theory
    predicate_logic --> formalized_proof
    proof_theory --> ordinal_analysis
    proof_theory --> formalized_proof
    proof_theory --> reverse_math
    model_theory --> forcing
    recursion_theory --> computability
    recursion_theory --> complexity
    forcing --> large_cardinal
    computability --> complexity
    computability --> algorithmic_information
    computability --> recursion_theory
    complexity --> cryptographic_protocol
    complexity --> provable_security
    type_theory --> formalized_proof
    type_theory --> homotopy_type_theory
    type_theory --> categorical_logic
    probability_measure --> random_variable
    probability_measure --> bayes_theorem
    probability_measure --> conditional_probability
    probability_measure --> stochastic_process
    probability_measure --> information
    probability_measure --> differential_privacy
    probability_measure --> risk_neutral
    random_variable --> probability_distribution
    random_variable --> expectation
    random_variable --> stochastic_process
    probability_distribution --> central_limit_theorem
    probability_distribution --> statistical_inference
    probability_distribution --> stochastic_optimization
    probability_distribution --> shannon_entropy
    probability_distribution --> credit_risk
    probability_distribution --> population_genetics
    expectation --> variance
    expectation --> law_of_large_numbers
    expectation --> shannon_entropy
    conditional_probability --> bayes_theorem
    bayes_theorem --> bayesian_inference
    stochastic_process --> markov_chain
    stochastic_process --> martingale
    stochastic_process --> brownian_motion
    stochastic_process --> time_series_analysis
    stochastic_process --> kalman_filter
    stochastic_process --> coalescent_theory
    markov_chain --> binomial_tree
    markov_chain --> phylogenetics
    martingale --> stochastic_calculus
    martingale --> risk_neutral
    brownian_motion --> stochastic_calculus
    law_of_large_numbers --> monte_carlo_simulation
    statistical_inference --> parameter_estimation
    statistical_inference --> hypothesis_testing
    statistical_inference --> regression_analysis
    statistical_inference --> bayesian_inference
    statistical_inference --> side_channel
    parameter_estimation --> maximum_likelihood
    parameter_estimation --> adaptive_control
    parameter_estimation --> system_identification
    parameter_estimation --> stochastic_volatility
    regression_analysis --> time_series_analysis
    bayesian_inference --> kalman_filter
    variance --> central_limit_theorem
    variance --> pca
    optimization_problem --> convex_function
    optimization_problem --> gradient_descent
    optimization_problem --> lagrange_multiplier
    optimization_problem --> linear_programming
    optimization_problem --> convex_optimization
    optimization_problem --> dynamic_programming
    optimization_problem --> stochastic_optimization
    optimization_problem --> nonlinear_programming
    optimization_problem --> mpc
    convex_set --> convex_function
    convex_function --> convex_optimization
    convex_function --> gradient_descent
    convex_function --> kl_divergence
    gradient --> gradient_descent
    gradient --> newton_method
    gradient --> conjugate_gradient
    gradient --> lagrange_multiplier
    gradient --> nonlinear_programming
    hessian_matrix --> newton_method
    gradient_descent --> gradient_boosting
    gradient_descent --> neural_network
    gradient_descent --> adam_optimizer
    lagrange_multiplier --> kkt_conditions
    kkt_conditions --> interior_point_method
    convex_optimization --> kkt_conditions
    convex_optimization --> interior_point_method
    convex_optimization --> quadratic_programming
    convex_optimization --> rate_distortion
    linear_programming --> simplex_method
    linear_programming --> integer_programming
    simplex_method --> interior_point_method
    dynamic_programming --> optimal_control
    dynamic_programming --> reinforcement_learning
    optimal_control --> lqr_control
    optimal_control --> mpc
    quadratic_programming --> portfolio_optimization
    control_system --> transfer_function
    control_system --> state_space
    control_system --> feedback_control
    control_system --> nonlinear_control
    control_system --> adaptive_control
    control_system --> system_identification
    transfer_function --> bode_plot
    transfer_function --> root_locus
    transfer_function --> feedback_control
    transfer_function --> pid_controller
    state_space --> state_feedback
    state_space --> observability
    state_space --> controllability
    state_space --> state_observer
    state_space --> mpc
    feedback_control --> pid_controller
    feedback_control --> stability_analysis
    stability_analysis --> robust_control
    bode_plot --> nyquist_criterion
    nyquist_criterion --> robust_control
    controllability --> state_feedback
    observability --> state_observer
    state_feedback --> lqr_control
    state_observer --> kalman_filter
    lqr_control --> mpc
    information --> shannon_entropy
    information --> quantum_crypto
    shannon_entropy --> mutual_information
    shannon_entropy --> kl_divergence
    shannon_entropy --> source_coding
    shannon_entropy --> data_compression
    shannon_entropy --> rate_distortion
    shannon_entropy --> cryptographic_protocol
    shannon_entropy --> quantum_information
    shannon_entropy --> algorithmic_information
    mutual_information --> channel_capacity
    source_coding --> huffman_coding
    source_coding --> arithmetic_coding
    channel_capacity --> network_information
    channel_coding --> channel_capacity
    channel_coding --> error_correction
    error_correction --> reed_solomon
    error_correction --> ldpc_code
    data_compression --> lossy_compression
    rate_distortion --> lossy_compression
    cryptographic_protocol --> zero_knowledge_proof
    quantum_mechanics --> quantum_information
    quantum_mechanics --> quantum_crypto
    quantum_mechanics --> schrodinger_equation
    quantum_mechanics --> path_integral
    symmetric_encryption --> aes
    symmetric_encryption --> mac
    aes --> side_channel
    public_key --> rsa
    public_key --> diffie_hellman
    public_key --> elliptic_curve_crypto
    public_key --> digital_signature
    public_key --> homomorphic_encryption
    public_key --> identity_based
    hash_function --> digital_signature
    hash_function --> mac
    hash_function --> blockchain_consensus
    digital_signature --> blockchain_consensus
    zero_knowledge_proof --> zk_snarks
    lattice_based_crypto --> post_quantum
    stochastic_calculus --> ito_calculus
    stochastic_calculus --> black_scholes
    ito_calculus --> ito_lemma
    ito_calculus --> sde
    ito_lemma --> black_scholes
    sde --> monte_carlo_simulation
    sde --> stochastic_volatility
    sde --> interest_rate_model
    black_scholes --> option_pricing
    risk_neutral --> black_scholes
    risk_neutral --> fundamental_theorem
    option_pricing --> greeks
    option_pricing --> implied_volatility
    greeks --> risk_management
    implied_volatility --> volatility_smile
    stochastic_volatility --> volatility_smile
    stochastic_volatility --> heston_model
    monte_carlo_simulation --> american_option
    american_option --> binomial_tree
    population_dynamics --> logistic_growth
    population_dynamics --> sir_model
    population_dynamics --> evolutionary_dynamics
    logistic_growth --> predator_prey
    nonlinear_dynamics --> logistic_growth
    nonlinear_dynamics --> chaos_theory
    nonlinear_dynamics --> bifurcation_theory
    predator_prey --> lotka_volterra
    sir_model --> seir_model
    reaction_diffusion --> turing_pattern
    reaction_diffusion --> chemotaxis
    turing_pattern --> morphogenesis
    evolutionary_dynamics --> replicator_dynamics
    replicator_dynamics --> ess
    population_genetics --> coalescent_theory
    neural_dynamics --> hodgkin_huxley
    bifurcation_theory --> neural_dynamics
    finite_difference --> numerical_ode
    finite_element --> adaptive_mesh
    sparse_matrix --> conjugate_gradient_method
    iterative_method --> conjugate_gradient_method
    iterative_method --> multigrid
    iterative_method --> preconditioner
    numerical_ode --> runge_kutta
    classical_mechanics --> lagrangian
    lagrangian --> hamiltonian
    hamiltonian --> hamiltonian_system
    hamiltonian_system --> integrable_system
    path_integral --> quantum_field_theory
    statistical_mechanics --> phase_transition
    statistical_mechanics --> turbulence
    renormalization --> phase_transition
    fluid_dynamics --> turbulence
    quantum_field_theory --> renormalization
    quantum_field_theory --> conformal_field_theory
    conformal_field_theory --> string_theory
    supersymmetry --> string_theory
    data_preprocessing --> feature_engineering
    decision_tree --> random_forest
    random_forest --> gradient_boosting
    neural_network --> backpropagation
    neural_network --> batch_normalization
    neural_network --> dropout
    neural_network --> autoencoder
    backpropagation --> deep_learning
    deep_learning --> cnn
    deep_learning --> rnn
    deep_learning --> gan
    rnn --> lstm
    lstm --> attention
    attention --> transformer
    higher_category --> infinity_category
    simplicial_set --> infinity_category
    model_category --> infinity_category
    abelian_category --> derived_category
    abelian_category --> triangulated_category
    abelian_category --> derived_functor_cat
    triangulated_category --> derived_category
    triangulated_category --> t_structure
    adjoint_functor --> kan_extension
    monoidal_category --> enriched_category
    monoidal_category --> bicategory
    2_category --> higher_category
    2_category --> bicategory
    fibered_category --> stack_category
    limits_colimits --> kan_extension
    yoneda_lemma --> representable_functor
    bicategory --> higher_category
    sheaf_cohomology --> local_cohomology
    sheaf_cohomology --> duality_cohomology
    sheaf_cohomology --> intersection_cohomology
    sheaf_cohomology --> etale_cohomology
    derived_category --> local_cohomology
    derived_category --> hypercohomology
    derived_category --> duality_cohomology
    derived_category --> perfect_complex
    derived_category --> tilting_theory
    derived_category --> t_structure
    derived_category --> koszul_duality
    derived_category --> derived_algebraic_geometry
    spectral_sequence --> hypercohomology
    t_structure --> perverse_sheaf
    intersection_cohomology --> perverse_sheaf
    ext_functor --> koszul_duality
    stack_category --> algebraic_stack
    algebraic_stack --> deligne_mumford
    algebraic_stack --> moduli_stack
    moduli_space --> moduli_stack
    de_rham_cohomology --> crystalline_cohomology
    de_rham_cohomology --> hodge_theory
    chow_ring --> intersection_theory
    biration_geometry --> minimal_model
    intersection_theory --> minimal_model
    infinity_category --> derived_algebraic_geometry
    infinity_category --> homotopy_type_theory
    representation_lie_algebra --> highest_weight
    representation_lie_algebra --> mackey_theory
    representation_lie_algebra --> langlands_program
    representation_lie_algebra --> automorphic_form
    highest_weight --> category_O
    highest_weight --> weight_theory
    perverse_sheaf --> geometric_representation
    induced_representation --> mackey_theory
    geometric_representation --> borel_weil
    abelian_variety --> elliptic_curve
    p_adic_number --> local_global
    etale_cohomology --> weil_conjecture
    zeta_function --> weil_conjecture
    zeta_function --> l_function
    symplectic_manifold --> symplectic_geometry
    intuitionistic_logic --> constructive_mathematics